# Generated by scripts/update-formula.sh during the release. Do not edit by
# hand: the next release will overwrite it.
class Prefixtool < Formula
  desc "Inspect, split and carve up IPv4 and IPv6 prefixes"
  homepage "https://github.com/jiphex/network-prefix-cli"
  version "1.0.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/jiphex/network-prefix-cli/releases/download/v1.0.0/prefixtool-v1.0.0-aarch64-apple-darwin.tar.gz"
      sha256 "5295a0dee9ec881a04085aadb9ee8a4e0f249ff1c1ad0b18952200d4ea0f65fd"
    end
    on_intel do
      url "https://github.com/jiphex/network-prefix-cli/releases/download/v1.0.0/prefixtool-v1.0.0-x86_64-apple-darwin.tar.gz"
      sha256 "2bee4b8d0da84199013bdde110eb4c99b3b8b995125b42a764ce9fad42cf1169"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/jiphex/network-prefix-cli/releases/download/v1.0.0/prefixtool-v1.0.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "8ee4b981df03026c58bf69cb31d6c8f65563c155a3f85fa72fdf99925408a16c"
    end
    on_intel do
      url "https://github.com/jiphex/network-prefix-cli/releases/download/v1.0.0/prefixtool-v1.0.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "9fd1d2166d6df81273932cc9f1c0b33500356b231a55e8d474146509552c0745"
    end
  end

  def install
    bin.install "prefixtool"
  end

  test do
    assert_match "prefixtool #{version}", shell_output("#{bin}/prefixtool --version")
    assert_equal "2001:db8::/64\n",
                 shell_output("#{bin}/prefixtool 2001:db8::/52 /64 --quiet --limit 1")
  end
end
