# Generated by scripts/update-formula.sh during the release. Do not edit by
# hand: the next release will overwrite it.
class Prefixtool < Formula
  desc "Inspect, split and carve up IPv4 and IPv6 prefixes"
  homepage "https://github.com/jiphex/network-prefix-cli"
  version "0.0.7"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/jiphex/network-prefix-cli/releases/download/v0.0.7/prefixtool-v0.0.7-aarch64-apple-darwin.tar.gz"
      sha256 "3c9269d76829d66c52787b6bd5928fe3c920e80be13f54d7973d9d381adc49b6"
    end
    on_intel do
      url "https://github.com/jiphex/network-prefix-cli/releases/download/v0.0.7/prefixtool-v0.0.7-x86_64-apple-darwin.tar.gz"
      sha256 "65e9c46ed2c6b09406637eed0b241a8a692c2742d5b14928be82311c969c9a10"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/jiphex/network-prefix-cli/releases/download/v0.0.7/prefixtool-v0.0.7-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "42adbe52f1c96a959f5b09d3307b9d71da6bb8fd791c499b18fa2a4c50b3ccb3"
    end
    on_intel do
      url "https://github.com/jiphex/network-prefix-cli/releases/download/v0.0.7/prefixtool-v0.0.7-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "2f4f57dc4593c5bcf95a12fbf8b8080712380d26e1c9fdbe10bde8dd54a007c7"
    end
  end

  def install
    bin.install "prefixtool"
  end

  test do
    assert_match "prefixtool #{version}", shell_output("#{bin}/prefixtool --version")
    assert_equal "2001:db8::/64\n",
                 shell_output("#{bin}/prefixtool 2001:db8::/52 /64 --quiet --limit 1")
  end
end
