# Generated by scripts/update-formula.sh during the release. Do not edit by
# hand: the next release will overwrite it.
class Prefixtool < Formula
  desc "Inspect, split and carve up IPv4 and IPv6 prefixes"
  homepage "https://github.com/jiphex/network-prefix-cli"
  version "0.0.4"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/jiphex/network-prefix-cli/releases/download/v0.0.4/prefixtool-v0.0.4-aarch64-apple-darwin.tar.gz"
      sha256 "51944e448e1bc7fcd81fa3c80cde5d27a4ece2add374887ffec7b9752e19e955"
    end
    on_intel do
      url "https://github.com/jiphex/network-prefix-cli/releases/download/v0.0.4/prefixtool-v0.0.4-x86_64-apple-darwin.tar.gz"
      sha256 "c2d5ce60bcd9f86eecb743aa989c847c75a5a0b887f9065f40544379ec0e2b5b"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/jiphex/network-prefix-cli/releases/download/v0.0.4/prefixtool-v0.0.4-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "739c16cad82f1f30e068b38d78e17dbf2cd63a1ca1e55f7df7fa20d69dec2138"
    end
    on_intel do
      url "https://github.com/jiphex/network-prefix-cli/releases/download/v0.0.4/prefixtool-v0.0.4-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "b9b115adb783b1c0ab1c86555c83de8cde348840ef00509a484371599c837fb2"
    end
  end

  def install
    bin.install "prefixtool"
  end

  test do
    assert_match "prefixtool #{version}", shell_output("#{bin}/prefixtool --version")
    assert_equal "2001:db8::/64\n",
                 shell_output("#{bin}/prefixtool 2001:db8::/52 /64 --quiet --limit 1")
  end
end
