#!/bin/sh
#
# Regenerate the Homebrew formula from a directory of built release archives.
#
# Every release ships a .sha256 next to each archive, so the checksums the
# formula needs are already sitting in the dist directory - there is no need to
# download anything back from GitHub to work them out.
#
# Usage: scripts/update-formula.sh <version> <dist-dir> [output-file]

set -eu

version=${1:-}
dist=${2:-}
out=${3:-Formula/prefixtool.rb}

if [ -z "$version" ] || [ -z "$dist" ]; then
	echo "usage: $0 <version> <dist-dir> [output-file]" >&2
	exit 1
fi

repo=jiphex/network-prefix-cli
tag="v$version"

# Read the checksum out of the .sha256 file that ships beside each archive.
sha_for() {
	file="$dist/prefixtool-$tag-$1.tar.gz.sha256"
	if [ ! -f "$file" ]; then
		echo "error: missing $file" >&2
		echo "       (has the $1 build run?)" >&2
		exit 1
	fi
	awk '{print $1; exit}' "$file"
}

# Linux uses the gnu builds for both architectures so the two stay symmetric.
mac_arm=$(sha_for aarch64-apple-darwin)
mac_intel=$(sha_for x86_64-apple-darwin)
linux_arm=$(sha_for aarch64-unknown-linux-gnu)
linux_intel=$(sha_for x86_64-unknown-linux-gnu)

url() {
	echo "https://github.com/$repo/releases/download/$tag/prefixtool-$tag-$1.tar.gz"
}

mkdir -p "$(dirname "$out")"
cat > "$out" <<EOF
# Generated by scripts/update-formula.sh during the release. Do not edit by
# hand: the next release will overwrite it.
class Prefixtool < Formula
  desc "Inspect, split and carve up IPv4 and IPv6 prefixes"
  homepage "https://github.com/$repo"
  version "$version"
  license "MIT"

  on_macos do
    on_arm do
      url "$(url aarch64-apple-darwin)"
      sha256 "$mac_arm"
    end
    on_intel do
      url "$(url x86_64-apple-darwin)"
      sha256 "$mac_intel"
    end
  end

  on_linux do
    on_arm do
      url "$(url aarch64-unknown-linux-gnu)"
      sha256 "$linux_arm"
    end
    on_intel do
      url "$(url x86_64-unknown-linux-gnu)"
      sha256 "$linux_intel"
    end
  end

  def install
    bin.install "prefixtool"
  end

  test do
    assert_match "prefixtool #{version}", shell_output("#{bin}/prefixtool --version")
    assert_equal "2001:db8::/64\n",
                 shell_output("#{bin}/prefixtool 2001:db8::/52 /64 --quiet --limit 1")
  end
end
EOF

echo "wrote $out for $tag"
